### ISSUE TITLE
Alpha9: A DeFi pension system, 10X better than a bank

### ISSUE THREAD

**Issue by altamira2050** [metacartel/dragon-quest#13]
## Help build a next gen DeFi pension system

We're launching a project that has the potential to have significant impact to society. A DeFi alternative to the pension system in Europe, and beyond.

We are following the basic tenets of DeFi, and applying them to a real estate pension fund, to enable new liquidity paradigms for elderly people, currently "underserved" (to say the least) by banks.

Our project is heavily based on data science and decentralized chains, to facilitate a circular economy based on real-estate collateral. We have a working prototype of the pricing engine, and the results show break-through financial performance compared to bank alternatives. We can beat bank's reverse mortgages by as much as 10X.

Besides the pricing engine, we have a couple of customer-facing sites in production. 

We're looking for hackers to join the project, and develop our crypto architecture design and vision, and help us kick-start a community.

## Team

The project has a Math's PhD helping on the data-science part, and an electrical engineer leading the project and helping with the Crypto/Economics part. 

## Skills wanted

_We're looking for people to help us in a number of areas:_

- [ ] Engineering: Help design the smart-contract architecture.
- [ ] Crypto-economics: Help design a decentralized real-estate tokenization, along the lines of Centrifuge, but in a scalable distributed way.
- [ ] Design: We need help across the board - develop a visual identity, develop UX and UI of our services/apps.
- [ ] Operations: Project management and performance Marketing. We'd like to run some market testing and validation. 
- [ ] Community builder: Someone with experience starting and rallying a community, with a goal to turn into DAO. 
- [ ] Culture / We need help with the "story telling" of our project. 
- [ ] Legal & Finance: We are looking for people with experience in launching ICOs, and understand legal implications of tokenizing real-estate assets, in a DeFI setting.

## Milestones
Here's what we'd like to achieve:
1. Have a prototype of the web3 app running on an ethereum testnet. 
2. Have a customer-facing landing page, to test market appetite
3. Launch a public open community to further development

Based on this, we are hoping to be able to raise capital to turn the project into a start-up supported by a communty that develops this professionally. 

## Communication

You can check the project at https://alpha9.network and at https://nuda.io
You can reach me at @alphablock9
https://t.me/alphablock9

## Why join?

We can make a huge difference to people who actually need it. Public pension systems across the world will be depleted with the coming age demographic inversion, and people need a fairer, better alternative to what's currently offered by banks.

Join a team with an ambition to have a social impact!

**Comment by viraj124** [comment]
Interested

**Comment by pet3r-pan** [comment]
👀

**Comment by NelsonMcKey** [comment]
Interested
